"""UniSchedule database migrations (introduced Phase 6C).

Zero-dependency, versioned migration runner for the SQLite deployment.
(Alembic/Flask-Migrate was evaluated and deliberately NOT adopted: no new
dependency, offline-friendly, and SQLite DDL here is simple enough that
explicit CREATE TABLE / ALTER TABLE statements are more reviewable than
autogenerated batches. A `schema_migrations` version table tracks applied
revisions, and every revision provides upgrade + downgrade.)

Usage (from the repository root). NEVER point --db at the live database
during development — the runner refuses the live path unless --allow-live
is passed explicitly:

    venv\\Scripts\\python.exe -m backend.migrate --db <path-to-copy.db> upgrade
    venv\\Scripts\\python.exe -m backend.migrate --db <path-to-copy.db> downgrade
    venv\\Scripts\\python.exe -m backend.migrate --db <path-to-copy.db> status
"""
import argparse
import importlib
import os
import pkgutil
import sqlite3
import sys
from datetime import datetime, timezone

from backend import migrations  # noqa: F401  (ensures package import path)
import backend.migrations.versions as versions_pkg

LIVE_DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "instance", "timetable.db")


def _load_revisions():
    revs = {}
    for mod in pkgutil.iter_modules(versions_pkg.__path__):
        m = importlib.import_module(f"{versions_pkg.__name__}.{mod.name}")
        if not getattr(m, "revision", None) or not hasattr(m, "upgrade"):
            continue
        revs[m.revision] = m
    # Order by down_revision chain (single linear history).
    ordered, seen = [], set()

    def visit(rev):
        if rev in seen or rev not in revs:
            return
        parent = getattr(revs[rev], "down_revision", None)
        if parent:
            visit(parent)
        seen.add(rev)
        ordered.append(rev)

    for rev in sorted(revs):
        visit(rev)
    return [(r, revs[r]) for r in ordered]


def _ensure_version_table(conn):
    conn.execute("CREATE TABLE IF NOT EXISTS schema_migrations ("
                 "revision VARCHAR(80) PRIMARY KEY, "
                 "applied_at VARCHAR(40) NOT NULL)")


def applied_revisions(conn):
    _ensure_version_table(conn)
    return {r[0] for r in conn.execute("SELECT revision FROM schema_migrations")}


def cmd_status(conn):
    applied = applied_revisions(conn)
    for rev, mod in _load_revisions():
        state = "applied" if rev in applied else "pending"
        print(f"{rev:30s} {state:10s} {getattr(mod, 'description', '')}")
    return 0


def cmd_upgrade(conn):
    applied = applied_revisions(conn)
    did = 0
    for rev, mod in _load_revisions():
        if rev in applied:
            continue
        mod.upgrade(conn)
        conn.execute("INSERT INTO schema_migrations (revision, applied_at) VALUES (?, ?)",
                     (rev, datetime.now(timezone.utc).isoformat()))
        conn.commit()
        print(f"upgraded {rev}")
        did += 1
    if not did:
        print("already up to date")
    return 0


def cmd_downgrade(conn, args):
    applied = applied_revisions(conn)
    chain = [(r, m) for r, m in _load_revisions() if r in applied]
    if not chain:
        print("nothing applied — nothing to downgrade")
        return 0
    target = args.to
    while chain and (target is None or chain[-1][0] != target):
        rev, mod = chain.pop()
        if not hasattr(mod, "downgrade"):
            print(f"revision {rev} has no downgrade — aborting")
            return 1
        if target is not None and rev == target:
            chain.append((rev, mod))
            break
        mod.downgrade(conn)
        conn.execute("DELETE FROM schema_migrations WHERE revision = ?", (rev,))
        conn.commit()
        print(f"downgraded {rev}")
        if target is None:
            break
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description="UniSchedule DB migrations")
    parser.add_argument("--db", required=True, help="SQLite file to migrate (a COPY, never live)")
    parser.add_argument("--allow-live", action="store_true",
                        help="Required to touch the live backend/instance/timetable.db")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status")
    sub.add_parser("upgrade")
    down = sub.add_parser("downgrade")
    down.add_argument("--to", default=None, help="downgrade down to (but not including) revision")
    args = parser.parse_args(argv)

    live = os.path.abspath(LIVE_DB) == os.path.abspath(args.db)
    if live and not args.allow_live:
        print(f"REFUSED: {args.db} is the live database. "
              f"Migrate a copy, or pass --allow-live explicitly.")
        return 2
    conn = sqlite3.connect(args.db)
    try:
        if args.command == "status":
            return cmd_status(conn)
        if args.command == "upgrade":
            return cmd_upgrade(conn)
        if args.command == "downgrade":
            return cmd_downgrade(conn, args)
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
